language: java
jdk:
  - oraclejdk11
os:
  - linux

addons:
  mariadb: '10.4'

env:
  - DOCKER_COMPOSE_VERSION=3.0.0
services:
  - docker

git:
  depth: 1
  quiet: true

before_script:
  - sudo mysql -e 'CREATE DATABASE refactoringtest'

jobs:
  include:
    - stage: Test
      name: "Run refactoringml Tests"
      script:
      - mvn -f ../predicting-refactoring-ml/data-collection/pom.xml '-Dtest=refactoringml.*Test' test
     
    - name: "Run Integration Toyproject Tests"
      script:
      - mvn -f ../predicting-refactoring-ml/data-collection/pom.xml '-Dtest=integration.toyprojects.*Test' test

    - name: "Run Integration Realproject ApacheCommonsCli Tests"
      script:
      - mvn -f ../predicting-refactoring-ml/data-collection/pom.xml '-Dtest=integration.realprojects.ApacheCommonsCli*Test' test

    - name: "Run Integration Realproject ApacheCommonsCSV Tests"
      script:
      - mvn -f ../predicting-refactoring-ml/data-collection/pom.xml '-Dtest=integration.realprojects.ApacheCommonsCSV*Test' test
