version: '3'
services:
  socat:
    container_name: socat
    image: bobrik/socat
    command: TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock
    ports:
      - "1234:1234"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_URI="http://socat:1234"

  queue:
    image: rabbitmq:3.8-rc-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  import:
    build: .
    volumes:
      - .:/data-collection
    environment:
      - TASK=import
      - FILE_TO_IMPORT=
      - QUEUE_HOST=queue
      - DOCKER_URI=http://socat:1234
    depends_on:
      - queue

  worker:
    build: .
    volumes:
      - .:/data-collection
      - ./volumes/storage:/storage
    environment:
      - TASK=worker
      - QUEUE_HOST=queue
      - STORAGE_PATH=/storage
      - REF_URL="private"
      - REF_USER="private"
      - REF_DBPWD="private"
      - THRESHOLD=50
      - STORE_FILES=false
      - DOCKER_URI=http://socat:1234
    depends_on:
      - queue
      - import
